TugboatQA/docs

config.toml

This should correct the issue of clicking the logo not taking you back to the front page.

Uncomment baseURL

---

config.toml

I added a step to the deployment job to enable these for production

disable baseURL and googleAnalytics for local development

---

content/building-a-preview/administer-previews/change-or-update-previews.md

Updating the language on the "Change or Update Previews" page to specify Refresh/Rebuild process faster/slower relative to Base Preview use.

Fixes #143 - Update language to include Base Preview use

---

content/setting-up-tugboat/select-repo-settings.md

Adding a callout to the Repository Settings page in the docs site to direct people to the article where we explain setting up a Tugboat bot as a user that can post comments to the linked git provider.

Closes #145 : Add link to tugboat bot article to repo settings page

---

content/setting-up-services/service-images/using-tugboat-images.md

Fixing the broken link that Cathy pointed out on the Setting up Services -> Service Images -> Using Tugboat Images page.

Closes #146 : Fix broken link to Tugboat images page

---

content/setting-up-tugboat/connect-with-your-provider.md

In the GitLab integration details, Prettier was making some changes that introduced extra spaces and made Hugo render the markdown in the "Off by default" section as a separate paragraph. This is me attempting to remove the spaces manually and see if that fixes the way the markdown rendering creates the HTML, and therefore fixes the formatting issue.

Remove spaces in GitLab integration details

---

content/starter-configs/tutorials/drupal-8.md

Found what appears to be a syntax error in the examples for Drupal 8.

Fixes syntax errors in Drupal 8 example

---

layouts/partials/header.html
layouts/partials/new-google-analytics.html

Couldn't figure out where the template stuff is generated in Hugo in order to modify it, so I switched the template to a `partial`, and created a new `partial`, used the official Hugo template file from the gohugo project here to generate the partial: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html
From here, I modified what the partial should generate to match the Google Analytics help article for cross-property tracking: https://support.google.com/analytics/answer/1034342?hl=en
Once we get these GA updates configured on all of Tugboat's properties, we should be able to track traffic/conversions across properties.

Add other Tugboat properties to GA tracking

---

content/faq/find-tugboat-ids.md
content/reference/tugboat-images.md
content/setting-up-services/how-to-set-up-services/specify-a-service-image.md
content/tugboat-cli/use-the-cli.md

There are two references I can't change because they rely on external services to change their branch names (Pantheon: https://pantheon.io/docs/terminus/install#terminus-installer-phar     and     PHP/Docker: https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions ). There are also some references within the Hugo Learn theme, as it's the base branch used all over within the theme.
I think this may be the best we can do for the moment.

Change `master` branch references to `main` branch

---

themes/hugo-theme-learn/static/css/theme.css

Made a new style for a "Premium Tier Feature" callout (referred to as a "notice" shortcode in this Hugo theme). 
My instinct says this should live in a custom .css somewhere instead of just appending it to the theme's .css, in the event that we ever update the theme and accidentally blow away this custom style. But I couldn't quickly figure out where that should be - i.e. where Hugo would know to look for it - and didn't want to spend too much time on this.
If we want to merge this, I can then use this notice style to add a note to the "Preview IP Filtering" feature we're documenting in #210 and denote that it's an enterprise-only feature.
I did validate that it works locally - here's what it looks like:

Create custom notice shortcode styling for premium tier features

---

content/reference/tugboat-configuration.md
content/setting-up-services/how-to-set-up-services/leverage-service-commands.md
content/setting-up-services/how-to-set-up-services/running-a-background-process.md
content/troubleshooting/preview-built-problem.md
content/troubleshooting/preview-wont-build.md

I've added documentation for the new service commands, `online`, `start`, and `clone`, and after chatting about these with Ben, have concluded it's time to build out the `ready` command documentation more so it has parity with the rest of the service commands. So I've added documentation for that here, too.
I've added content in several place in the docs site (check out changed files) but have not touched the "How Previews Work -> The Build Process Explained" documentation. I'm not sure that the documentation there needs to change, actually. Although I'm wondering if I should build out more content about the Build Snapshot, as we're now referencing that for some of the new service command documentation. I'm also uncertain about whether we need to update the build phase diagram, or create …

Add documentation for online, start, clone, ready

---

content/_index.md

I've been thinking about the API documentation, and I'd like to get the link here on the docs front page as a starting point.
Bigger-picture, it would be good to create some cross-links to the documentation portal from the API docs, I think. The endpoints are all documented, but the API docs assume that people who are consuming them are familiar with how Tugboat works, and assume developers are familiar with what the docs mean when we say things like "projects" "repositories" "previews" "services" and "visual diffs." 
I think an incremental improvement we could offer is to provide links from the API docs to the main docs site at the beginning of each API doc section for "concept" explanation, so we're not trying to maintain that info in two places. Currently, the "concepts" are documented …

Add API documentation link to front page

---

content/troubleshooting/fix-problem-x.md

Added documentation for this issue to the "Troubleshooting" section of the docs, using the details captured in our internal issue + the external article from the other org that reported similar issues. Does this accurately communicate the relevant details/fix?

Add a fix for GitHub repos failing to appear in Tugboat

---

content/setting-up-tugboat/select-repo-settings.md

When we were discussing the upcoming changes to Docker Hub, I noticed the list of third-party platforms on Docker's `Download rate limit` document: https://docs.master.dockerproject.org/docker-hub/download-rate-limit/
I'd like to add Tugboat to the list of third-party platforms there, but wanted to build out our documentation a bit more around Docker authentication before I do that.
Thoughts on whether this is a meaningful level of detail? (And do we want to hold off on merging this until this accurately reflects the state of the app re: a generic Tugboat authenticated user?)

Add more info around authenticating with a Docker registry

---

content/starter-configs/tutorials/wordpress.md

Make sure rewrite and headers modules are enabled so pretty URLs work out of the box.
Install the minimum PHP tools so wordpress status doesn't flag missing dependencies

Update default apache tools

---

content/lighthouse/configure-lighthouse.md

Remove first-cpu-idle from Lighthouse docs; it's deprecated

---

content/building-a-preview/administer-previews/build-previews.md
content/building-a-preview/automate-previews/auto-generate.md

This came out of a mini show-and-tell I did with a customer on how to build when there are Composer conflicts, especially in long-lived feature branches.

Document Tugboat merging behavior

---

content/reference/tugboat-images.md

the current link for MariaDB in this page: https://docs.tugboatqa.com/reference/tugboat-images/ is https://docs.tugboatqa.com/reference/tugboat-images/#mysqlmariadbpercona, but the anchor is https://docs.tugboatqa.com/reference/tugboat-images/#mysql-mariadb-percona

Fix anchor for MySQL

---

content/setting-up-services/how-to-set-up-services/running-a-background-process.md

Alternatively, it could be changed to:
```markdown
To add your own background process that starts when the Service starts, create a directory in
`/etc/service` named `yourprocessname` and a script inside that directory named `run` to tell `runit` how to start your
```
But that's arguably messier.

Fix instruction by removing a stray word

---

content/reference/tugboat-images.md

#341 fix: use absolute path to solr binary

---

content/starter-configs/_index.md

Problem
- Contributed starter kits such as https://github.com/makers99/TugboatQA-WordPress-WooCommerce-Starter-Kit are not listed when following the link in the documentation.
Goal
- Encourage knowledge sharing with community contributed configurations.
Proposed solution
1. Change the link from the GitHub tag "starter-kit" in the TugboatQA organization to use the tag "tugboat-starter-kit" without restriction on organizations.

Changed link to GitHub tag "tugboat-starter-kit".

---

content/lighthouse/configure-lighthouse.md
content/starter-configs/tutorials/wordpress.md

Changes the link to documentation about Lighthouse custom configuration, with the aim of preventing customers to implement settings that are not supported by our Lighthouse version.

Link to Lighthouse documentation specific to our installed version

---

content/starter-configs/examples/gatsby.md

Makes an adjustment to the Gatsby `.tugboat/config.yml` config snippet. This is the same adjustment already made to Starter Configs > Code Snipptes > Install Node.js, which was done in https://github.com/TugboatQA/docs/pull/369.

docs: adjust node install snippet for gatsby

---

content/administer-tugboat-crew/_index.md
content/building-a-preview/_index.md
content/building-a-preview/administer-previews/_index.md
content/building-a-preview/automate-previews/_index.md
content/building-a-preview/preview-deep-dive/_index.md
content/building-a-preview/share-a-preview/_index.md
content/building-a-preview/work-with-base-previews/_index.md
content/faq/_index.md
content/lighthouse/_index.md
content/reference/_index.md
content/setting-up-services/_index.md
content/setting-up-services/how-to-set-up-services/_index.md
content/setting-up-services/service-images/_index.md
content/setting-up-tugboat/_index.md
content/starter-configs/_index.md
content/starter-configs/code-snippets/_index.md
content/starter-configs/examples/_index.md
content/starter-configs/tutorials/_index.md
content/troubleshooting/_index.md
content/tugboat-billing/_index.md
content/tugboat-cli/_index.md
content/visual-diffs/_index.md

Running `yarn build` gave me an error: `shortcode "children" must be closed or self-closed`
See https://github.com/gohugoio/hugo/issues/10838
Apparently hugo 0.111 is more restrictive, and hugo 0.111 is the default in e.g. debian 12 repos (I'm using ddev). This should work in any previous version of hugo though.

Fix shortcode "children" must be closed or self-closed

---

content/building-a-preview/preview-deep-dive/inside-a-preview.md

I tried using `${TUGBOAT_SMTP}` for sending mails via port 2525 and I got a connection refused.
@jcbain confirmed only 25 and 587 are captured.

fix: Corrected smtp docs, only ports 25 and 587 are captured for display

---

assets/css/theme-tugboat.css

fix: ensure descenders are not cropped in headings
