- docs/book.json
> Add anchor links next to headings #18

- build-script/helper-makefile/index.md
- package.json
> Fix link to makefile source

- advanced/cli/index.md
> Add CLI keyword search

- reference/environment-variables/index.md
Depends on https://github.com/Lullabot/tugboat/pull/2719
> Add pull request number envvars

- reference/tugboat-configuration/index.md
Do not merge this until the next Tugboat release
> Update HTTP/HTTPS defaults to reflect upcoming release

- reference/environment-variables/index.md
Closes https://github.com/Lullabot/tugboat/issues/2786
> Update the list of available environment variables

- faq/index.md
Added a FAQ for this question...
> Can I use my own images in Tugboat?

- administering-tugboat-crew/index.md
- building-a-preview/index.md
- setting-up-tugboat/index.md
> Minor Tweaks

- content/building-a-preview/preview-deep-dive/how-previews-work.md
- content/troubleshooting/fix-problem-x.md
> Add info around snapshot stopping containers

- content/reference/environment-variables.md
Documentation update for https://github.com/Lullabot/tugboat/pull/3474
Do not merge until that has been released
> Add service aliases and domain envvars

- content/reference/tugboat-configuration.md
> Fix broken links

- content/starter-configs/tutorials/drupal-8.md
> Add examples for dealing with Drupal private files and config #21

- content/starter-configs/code-snippets/generic-lamp.md
> Make LAMP all caps

- content/tugboat-cli/install-the-cli.md
> Add CLI Homebrew details

- content/_index.md
- layouts/partials/menu-footer.html
- layouts/shortcodes/button.html
- static/css/theme-tugboat.css
@dacharyc do we want some utm params on these links?
> Add a link to the www site from docs

- content/reference/tugboat-community-images.md
- layouts/shortcodes/icon.html
> Add a Community Images page. #217

- content/starter-configs/tutorials/drupal-9.md
- content/starter-configs/tutorials/pantheon.md
- content/starter-configs/tutorials/testery.md
> Add a starter config for Drupal 9

- content/setting-up-tugboat/create-a-tugboat-config-file.md
> Rewrite config page to add parameter option, provide more details

- content/setting-up-tugboat/connect-with-your-provider.md
- content/troubleshooting/fix-problem-x.md
Tagging you for review, Ben, because this documentation is for your "needs documentation" ticket (I'm about to archive it) and tagging you, James, because this info is mostly from your excellent gist and I'd love you to review for accuracy/details.
> Add API token authorization details

- content/reference/environment-variables.md
These variables were added by https://github.com/Lullabot/tugboat/pull/3829
> Add new environment variables to reference

- content/lighthouse/configure-lighthouse.md
- content/setting-up-tugboat/select-repo-settings.md
- content/tugboat-billing/change-tugboat-plan.md
- content/tugboat-billing/tugboat-pricing.md
- content/visual-diffs/configure-visual-diffs.md
- themes/hugo-theme-learn/static/css/theme.css
> Update language around Tugboat plans

- content/starter-configs/_index.md
This blog post is great!!! Would have saved me a fair amount of time had I seen it earlier... :laughing:  Just suggesting you highlight it somewhere?
> Include link to 10 tips blog post.

- content/setting-up-tugboat/select-repo-settings.md
> Private previews

- content/reference/tugboat-images.md
> Document new images

- content/setting-up-services/how-to-set-up-services/custom-environment-variables.md
> Clarify documentation around envvars in tugboat cli usage #293

- content/starter-configs/code-snippets/install-nodejs.md
> #278 how to install Node.js

- .prettierignore
- content/reference/environment-variables.md
- static/css/theme-tugboat.css
> #261 document the DOCROOT environment variable

- content/faq/common-questions.md
> #52 document about http basic auth

- content/tugboat-billing/cancel-billing.md
- content/tugboat-billing/change-billing-information.md
- content/tugboat-billing/change-tugboat-plan.md
> Add a notice about Tugboat Premium on billing pages

- content/reference/tugboat-images.md
Follow-up from https://github.com/Lullabot/tugboat/issues/4666 and https://github.com/TugboatQA/images/issues/85: Document the ability to restart the MySQL service.
> Documenting modifying MySQL cnf file and restarting the service.

- content/tugboat-cli/set-an-access-token.md
> feat: document 1Password CLI shell plugin #342

- content/building-a-preview/preview-deep-dive/how-previews-work.md
- content/building-a-preview/work-with-base-previews/building-new-previews.md
@q0rban Here are my suggested changes to the Tugboat docs. Thank you as always for your excellent help.
> Base preview option clarifications

- content/reference/tugboat-images.md
> feat: document new tugboatqa/cypress-included Docker image #348

- content/reference/tugboat-images.md
- content/setting-up-services/how-to-set-up-services/services-in-action.md
- content/starter-configs/code-snippets/import-mysql-database.md
- content/starter-configs/code-snippets/phpmyadmin.md
- content/starter-configs/examples/generic-lamp.md
- content/starter-configs/tutorials/drupal-7.md
- content/starter-configs/tutorials/drupal-8.md
- content/starter-configs/tutorials/wordpress.md
> fix: update docs surrounding mysql tags #353

- content/starter-configs/examples/gatsby.md
- content/starter-configs/tutorials/wordpress.md
> Add a Gatsby starter config

- content/starter-configs/tutorials/drupal-10.md
> Create Drupal 10 page

- content/starter-configs/code-snippets/install-nodejs.md
> fix: Update code snippet to install Node JS

- content/starter-configs/tutorials/lagoon.md
> Start a Lagoon tutorial.

- content/starter-configs/tutorials/drupal-10.md
- content/starter-configs/tutorials/drupal-8.md
- content/starter-configs/tutorials/drupal-9.md
> fix: don't symlink drupal config dir, use settings instead #378

- content/setting-up-services/how-to-set-up-services/services-in-action.md
- content/starter-configs/tutorials/drupal-8.md
- content/starter-configs/tutorials/pantheon.md
> fix: remove references to drush-launcher #382

- .tugboat/config.yml
- package-lock.json
- yarn.lock
See #381 - Required to run the example env var generator script.
> Install node.js

- content/reference/tugboat-images.md
> #385 feat: add postgis documentation

- content/starter-configs/tutorials/laravel.md
> Laravel tutorial, fixes #388

- .github/workflows/link-checker.yml
- .github/workflows/prettier.yml
- content/starter-configs/code-snippets/memcache.md
Adds a note on how to update the Tugboat config.yml and Drupal settings to work with Memcache on Tugboat
> Installing memcache in the PHP container on Tugboat QA

- content/reference/tugboat-configuration.md
- static/config-schema.json
> fix: update screenshot timeout to 60 instead of 120 #414
